<?php

namespace Bigfoot\Bundle\ContentBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AttributeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttributeRepository extends EntityRepository
{
    /**
     * @param $type
     * @return array
     */
    public function findByType($type)
    {
        return $this
            ->createQueryBuilder('a')
            ->where('a.type = :type')
            ->orderBy('a.label')
            ->setParameter(':type', $type);
    }
}
