<?php

namespace Bigfoot\Bundle\ContentBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * WidgetParameterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WidgetParameterRepository extends EntityRepository
{
}
