<?php

namespace Bigfoot\Bundle\ContentBundle\Entity\Page;

use Doctrine\ORM\EntityRepository;

/**
 * Sidebar4Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Sidebar4Repository extends EntityRepository
{
    public function findOneByPageSidebar($page, $sidebar)
    {
        return $this
            ->createQueryBuilder('b')
            ->where('b.page = :page')
            ->andWhere('b.sidebar = :sidebar')
            ->setParameter('page', $page)
            ->setParameter('sidebar', $sidebar)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
